language: go
go:
  - tip
install:
  - go get -t github.com/FreifunkBremen/yanic/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - ./.test-coverage
  - go install github.com/FreifunkBremen/yanic/cmd/yanic
  - go install github.com/FreifunkBremen/yanic/cmd/yanic-query
before_deploy:
  - ./.build-packages
deploy:
  provider: packagecloud
  repository: yanic
  username: FreifunkBremen
#  on:
#    branch: master
  
